Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using zaliczenia.Data;
using zaliczenia.Models;


public class CarsController : Controller
{
    private readonly ApplicationDbContext _context;

    public CarsController(ApplicationDbContext context)
    {
        _context = context;
    }

    [Authorize]
    public IActionResult Index()
    {
        return View(Car.GetCars());
    }
}

Controllers/RentalFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using zaliczenia.Data;
using zaliczenia.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

public class RentalFormsController : Controller
{
    private UserManager<IdentityUser> _userManager;

    private readonly ApplicationDbContext _context;

    public RentalFormsController(UserManager<IdentityUser> userManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _context = context;
    }

    
    [Authorize(Policy = "AdminPolicy")]
    public IActionResult Index()
    {
        var rentalForms = _context.RentalForms.OrderByDescending(r => r.Id).ToList();
        return View(rentalForms);
    }

    [HttpGet]
    [Authorize]
    public IActionResult Details(int id)
    {
        var car = Car.GetCars().FirstOrDefault(c => c.Id == id);
        if (car == null)
        {
            return NotFound();
        }

        var rentalForm = new RentalForm { CarId = car.Id };

        ViewBag.Car = car;

        return View(rentalForm);
    }

    [HttpPost]
    [Authorize]
    public IActionResult SubmitForm(RentalForm form)
    {
        var allCars = Car.GetCars();
        var car = allCars.FirstOrDefault(c => c.Id == form.CarId);
        var userId = _userManager.GetUserId(User);
        form.UserId = userId;

        if (car == null)
        {
            return NotFound();
        }

    
        _context.RentalForms.Add(form);
        _context.SaveChanges();
        TempData["SuccessMessage"] = "Twój formularz wynajmu został pomyślnie przesłany.";
        return RedirectToAction("Index", "Cars");
    }

    [HttpPost]
    [Authorize]
    [Authorize(Policy = "AdminPolicy")]
    public IActionResult Delete(int id)
    {
        var user = _userManager.GetUserId(User);

        Console.WriteLine(user);

        var rentalForm = _context.RentalForms.Find(id);

        if (rentalForm == null)
        {
            return NotFound();
        }

        _context.RentalForms.Remove(rentalForm);
        _context.SaveChanges();

        TempData["SuccessMessage"] = "Wynajem został pomyślnie usunięty.";
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Authorize(Policy = "AdminPolicy")]
    public IActionResult Edit(int id)
    {
        var rentalForm = _context.RentalForms.Find(id);

        if (rentalForm == null)
        {
            return NotFound();
        }

        // Optionally, you can retrieve related data like Car details if needed
        ViewBag.Car = Car.GetCars().FirstOrDefault(c => c.Id == rentalForm.CarId);

        return View(rentalForm);
    }

    [HttpPost]
    [Authorize(Policy = "AdminPolicy")]
    public IActionResult Edit(RentalForm form)
    {
 
        var existingForm = _context.RentalForms.Find(form.Id);

        if (existingForm == null)
        {
            return NotFound();
        }

        // Update existing form properties
        existingForm.Name = form.Name;
        existingForm.Email = form.Email;
        existingForm.Phone = form.Phone;
        existingForm.PickupDate = form.PickupDate;
        existingForm.LeavingDate = form.LeavingDate;

        _context.SaveChanges();

        TempData["SuccessMessage"] = "Formularz wynajmu został pomyślnie zaktualizowany.";
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - zaliczenia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/zaliczenia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wypozyczalnia aut</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Strona glowna</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Polityka prywatnosci</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">O nas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Samochody</a>
                    </li>

                    @if (User.Identity.Name == "admin@admin.pl")
                    {

                    <li class="nav-item">
                         <a class="nav-link" href="@Url.Action("Index", "RentalForms")">Wypożyczenia</a>
                    </li>
                     }
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["SuccessMessage"] != null)
            {
                <div class="alert alert-success">
                    @TempData["SuccessMessage"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-dark">
            &copy; 2024 - zaliczenia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Polityka prywatnosci</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>